-- Create the system_logs table
CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL,
  payload JSONB,
  error_message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE system_logs ENABLE ROW LEVEL SECURITY;

-- Admins can view and insert
CREATE POLICY "Admins can view system logs" ON system_logs FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Service can insert system logs" ON system_logs FOR INSERT WITH CHECK (true); -- Public/Service Role for inserts

-- Function to keep only the latest 150 rows
CREATE OR REPLACE FUNCTION truncate_system_logs()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM system_logs
  WHERE id NOT IN (
    SELECT id FROM system_logs
    ORDER BY created_at DESC
    LIMIT 150
  );
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to execute the truncate function after insert
CREATE TRIGGER trigger_truncate_system_logs
AFTER INSERT ON system_logs
FOR EACH ROW
EXECUTE FUNCTION truncate_system_logs();
